version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gymflow-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gymflow
      POSTGRES_USER: gymflow
      POSTGRES_PASSWORD: gymflow123
    ports:
      - "5433:5432"
    volumes:
      - gymflow_data:/var/lib/postgresql/data

volumes:
  gymflow_data: